language: java

cache:
  directories:
    - ${HOME}/.m2/repository/

matrix:
  include:
    # OpenJDK 11
    - dist: bionic
      jdk: openjdk11
    # Oracle JDK 11
    - dist: trusty
      jdk: oraclejdk11
    # OpenJDK 8
    - dist: trusty
      jdk: openjdk8
    # Oracle JDK 8
    - dist: trusty
      jdk: oraclejdk8

install: skip

script:
  - mvn -f "${TRAVIS_BUILD_DIR}/pom.xml" --batch-mode clean package
